"""Added cleanup table

Revision ID: 4c65cde24fb2
Revises: df17b772ce3f
Create Date: 2021-01-25 19:37:28.959102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c65cde24fb2'
down_revision = 'df17b772ce3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleanup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lastCleanup', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cleanup')
    # ### end Alembic commands ###
