"""changed password to text.

Revision ID: 4ea1d96d21ae
Revises: 4f32dff5f68d
Create Date: 2020-12-30 15:47:35.280361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea1d96d21ae'
down_revision = '4f32dff5f68d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    op.add_column('user', sa.Column('password', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
