"""Added api key to devices

Revision ID: 4f32dff5f68d
Revises: 23f7efa77ea5
Create Date: 2020-12-30 11:23:10.980904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f32dff5f68d'
down_revision = '23f7efa77ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('apiKey', sa.String(length=64), server_default='no-key', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'apiKey')
    # ### end Alembic commands ###
