"""Added device type

Revision ID: 5c3bacac73fe
Revises: 31b2ff78dd23
Create Date: 2020-12-31 15:14:52.219188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c3bacac73fe'
down_revision = '31b2ff78dd23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('type', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'type')
    # ### end Alembic commands ###
