"""added hub sessions

Revision ID: 9ef966af5ae6
Revises: b1c42cd0cf92
Create Date: 2021-01-16 15:15:30.330982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef966af5ae6'
down_revision = 'b1c42cd0cf92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hub_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sessionId', sa.LargeBinary(length=256), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hub_session')
    # ### end Alembic commands ###
