"""New sensors

Revision ID: b1c42cd0cf92
Revises: 5c3bacac73fe
Create Date: 2021-01-04 19:01:31.616341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c42cd0cf92'
down_revision = '5c3bacac73fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('accuracy', sa.Float(), nullable=True))
    op.add_column('sensor', sa.Column('suffix', sa.String(length=32), server_default='°C', nullable=False))
    op.add_column('sensor', sa.Column('target', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'target')
    op.drop_column('sensor', 'suffix')
    op.drop_column('sensor', 'accuracy')
    # ### end Alembic commands ###
