"""removed hub sessions

Revision ID: c9b0fc3a19d8
Revises: 47f865618dc0
Create Date: 2021-01-18 16:51:17.650883

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c9b0fc3a19d8'
down_revision = '47f865618dc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index('userId', table_name='hub_session')
    op.drop_table('hub_session')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hub_session',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sessionId', sa.BLOB(), nullable=False),
    sa.Column('time', mysql.DATETIME(), nullable=False),
    sa.Column('userId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], name='hub_session_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('userId', 'hub_session', ['userId'], unique=True)
    # ### end Alembic commands ###
