"""Back to the roots

Revision ID: cd018c8ffe6b
Revises: 4c65cde24fb2
Create Date: 2021-02-01 21:03:20.322946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cd018c8ffe6b'
down_revision = '4c65cde24fb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('value',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('timespan', sa.String(length=8), nullable=False),
    sa.Column('sensorId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sensorId'], ['sensor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('sensordata')
    op.drop_table('cleanup')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cleanup',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('lastCleanup', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('sensordata',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sensorId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('time', mysql.DATETIME(), nullable=False),
    sa.Column('value', mysql.FLOAT(), nullable=False),
    sa.ForeignKeyConstraint(['sensorId'], ['sensor.id'], name='sensordata_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('value')
    # ### end Alembic commands ###
