"""Added sensor type

Revision ID: df17b772ce3f
Revises: c9b0fc3a19d8
Create Date: 2021-01-22 18:28:19.184250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df17b772ce3f'
down_revision = 'c9b0fc3a19d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sensor', sa.Column('type', sa.String(length=32), server_default='reader', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sensor', 'type')
    # ### end Alembic commands ###
