"""Added user ID to hub session

Revision ID: f953cbfd2079
Revises: 9ef966af5ae6
Create Date: 2021-01-16 19:44:41.962561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f953cbfd2079'
down_revision = '9ef966af5ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hub_session', sa.Column('userId', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'hub_session', ['userId'])
    op.create_foreign_key(None, 'hub_session', 'user', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hub_session', type_='foreignkey')
    op.drop_constraint(None, 'hub_session', type_='unique')
    op.drop_column('hub_session', 'userId')
    # ### end Alembic commands ###
